version: "3.8"
services:
  php-apache-environment:
    container_name: frontend
    image: christojeffrey/wbd-tubes-1:1.0
    build:
      context: dockerfiles
      dockerfile: frontend.Dockerfile

    volumes:
      - ./src:/usr/src
    ports:
      - 8000:80
